ALTER SESSION SET nls_date_format = 'DD-MM-YYYY';
BEGIN
DBMS_RANDOM.seed('random_seed');
END;
/
set serveroutput on;

ALTER TABLE TWORZENIE_GRY DROP CONSTRAINT TWORZENIE_GRY_fk1;
ALTER TABLE TWORZENIE_GRY DROP CONSTRAINT TWORZENIE_GRY_fk2;
ALTER TABLE TWORZENIE_GRY DROP CONSTRAINT TWORZENIE_GRY_fk3;
ALTER TABLE KOMENTARZ_DO_RECENZJI DROP CONSTRAINT KOMENTARZ_DO_RECENZJI_fk1;
ALTER TABLE KOMENTARZ_DO_RECENZJI DROP CONSTRAINT KOMENTARZ_DO_RECENZJI_fk2;
ALTER TABLE RECENZJA DROP CONSTRAINT recenzja_fk1;
ALTER TABLE RECENZJA DROP CONSTRAINT recenzja_fk2;
ALTER TABLE RECENZJA DROP CONSTRAINT recenzja_fk3;
ALTER TABLE PORADNIK_DO_GRY DROP CONSTRAINT PORADNIK_DO_GRY_fk1;
ALTER TABLE PORADNIK_DO_GRY DROP CONSTRAINT PORADNIK_DO_GRY_fk2;
ALTER TABLE PORADNIK_DO_GRY DROP CONSTRAINT PORADNIK_DO_GRY_fk3;
ALTER TABLE KOMENTARZ_DO_GRY DROP CONSTRAINT KOMENTARZ_DO_GRY_fk1;
ALTER TABLE KOMENTARZ_DO_GRY DROP CONSTRAINT KOMENTARZ_DO_GRY_fk2;
ALTER TABLE WYDANIE_GRY DROP CONSTRAINT WYDANIE_GRY_fk1;
ALTER TABLE WYDANIE_GRY DROP CONSTRAINT WYDANIE_GRY_fk2;
ALTER TABLE WYDANIE_GRY DROP CONSTRAINT WYDANIE_GRY_fk3;

DROP TRIGGER KOMENTARZ_DO_RECENZJI_seq_trg;
DROP TABLE KOMENTARZ_DO_RECENZJI;
DROP SEQUENCE KOMENTARZ_DO_RECENZJI_seq;

DROP TRIGGER RECENZJA_seq_trg;
DROP TABLE RECENZJA;
DROP SEQUENCE RECENZJA_seq;

drop table TWORZENIE_GRY;

DROP TRIGGER PORADNIK_DO_GRY_seq_trg;
DROP TABLE PORADNIK_DO_GRY;
DROP SEQUENCE PORADNIK_DO_GRY_seq;

DROP TRIGGER KOMENTARZ_DO_GRY_seq_trg;
DROP TABLE KOMENTARZ_DO_GRY;
DROP SEQUENCE KOMENTARZ_DO_GRY_seq;

drop table WYDANIE_GRY;

DROP TRIGGER GRA_seq_trg;
DROP TABLE GRA;
DROP SEQUENCE GRA_seq;

DROP TRIGGER PLATFORMA_seq_trg;
DROP TABLE PLATFORMA;
DROP SEQUENCE PLATFORMA_seq;

DROP TRIGGER STUDIO_DEWELOPERSKIE_seq_trg;
DROP TABLE STUDIO_DEWELOPERSKIE;
DROP SEQUENCE STUDIO_DEWELOPERSKIE_seq;

DROP TRIGGER GATUNEK_seq_trg;
DROP TABLE GATUNEK;
DROP SEQUENCE GATUNEK_seq;


DROP TRIGGER WYDAWCA_seq_trg;
DROP TABLE WYDAWCA;
DROP SEQUENCE WYDAWCA_seq;


DROP TABLE UZYTKOWNIK;
DROP SEQUENCE UZYTKOWNIK_seq;
DROP TRIGGER UZYTKOWNIK_seq_trg;
--------------------------------------------------------------------------------

create table WYDAWCA(
  wydawca_id NUMBER,
  nazwa VARCHAR2(200)
  
);

CREATE SEQUENCE WYDAWCA_seq;
CREATE OR REPLACE TRIGGER WYDAWCA_seq_trg
BEFORE INSERT ON WYDAWCA
FOR EACH ROW
BEGIN
  :NEW.wydawca_id := WYDAWCA_seq.NEXTVAL;
END;
/
--------------------------------------------------------------------------------

create table UZYTKOWNIK (
  uzytkownik_id NUMBER,
  nazwa VARCHAR2(200)
);

CREATE SEQUENCE UZYTKOWNIK_seq;
CREATE OR REPLACE TRIGGER UZYTKOWNIK_seq_trg
BEFORE INSERT ON UZYTKOWNIK
FOR EACH ROW
BEGIN
  :NEW.uzytkownik_id := UZYTKOWNIK_seq.NEXTVAL;
END;
/
--------------------------------------------------------------------------------
create table GATUNEK (
  gatunek_id NUMBER,
  nazwa VARCHAR2(200)
);

CREATE SEQUENCE GATUNEK_seq;
CREATE OR REPLACE TRIGGER GATUNEK_seq_trg
BEFORE INSERT ON GATUNEK
FOR EACH ROW
BEGIN
  :NEW.gatunek_id := GATUNEK_seq.NEXTVAL;
END;
/
--------------------------------------------------------------------------------

create table STUDIO_DEWELOPERSKIE (
  studio_deweloperskie_id NUMBER,
  nazwa VARCHAR2(200)
);

CREATE SEQUENCE STUDIO_DEWELOPERSKIE_seq;
CREATE OR REPLACE TRIGGER STUDIO_DEWELOPERSKIE_seq_trg
BEFORE INSERT ON STUDIO_DEWELOPERSKIE
FOR EACH ROW
BEGIN
  :NEW.studio_deweloperskie_id := STUDIO_DEWELOPERSKIE_seq.NEXTVAL;
END;
/
--------------------------------------------------------------------------------

create table PLATFORMA (
  platforma_id NUMBER,
  nazwa VARCHAR2(200)
);

CREATE SEQUENCE PLATFORMA_seq;
CREATE OR REPLACE TRIGGER PLATFORMA_seq_trg
BEFORE INSERT ON PLATFORMA
FOR EACH ROW
BEGIN
  :NEW.platforma_id := PLATFORMA_seq.NEXTVAL;
END;
/
--------------------------------------------------------------------------------
create table GRA (
  gra_id NUMBER,
  nazwa VARCHAR2(200),
  gatunek_id NUMBER,
  tagi VARCHAR2(200)
);

CREATE SEQUENCE GRA_seq;
CREATE OR REPLACE TRIGGER GRA_seq_trg
BEFORE INSERT ON GRA
FOR EACH ROW
BEGIN
  :NEW.gra_id := GRA_seq.NEXTVAL;
END;
/
--------------------------------------------------------------------------------

create table WYDANIE_GRY (
  gra_id NUMBER,
  wydawca_id NUMBER,
  platforma_id NUMBER,
  data DATE
);

--------------------------------------------------------------------------------

create table KOMENTARZ_DO_GRY (
  komentarz_do_gry_id NUMBER,
  gra_id NUMBER,
  uzytkownik_id NUMBER,
  data DATE,
  tekst VARCHAR2(200)
);


CREATE SEQUENCE KOMENTARZ_DO_GRY_seq;
CREATE OR REPLACE TRIGGER KOMENTARZ_DO_GRY_seq_trg
BEFORE INSERT ON KOMENTARZ_DO_GRY
FOR EACH ROW
BEGIN
  :NEW.komentarz_do_gry_id := KOMENTARZ_DO_GRY_seq.NEXTVAL;
END;
/

--------------------------------------------------------------------------------
create table PORADNIK_DO_GRY (
  poradnik_do_gry_id NUMBER,
  uzytkownik_id NUMBER,
  gra_id NUMBER,
  platforma_id NUMBER,
  tekst VARCHAR2(200),
  tagi VARCHAR2(200)
);
CREATE SEQUENCE PORADNIK_DO_GRY_seq;
CREATE OR REPLACE TRIGGER PORADNIK_DO_GRY_seq_trg
BEFORE INSERT ON PORADNIK_DO_GRY
FOR EACH ROW
BEGIN
  :NEW.poradnik_do_gry_id := PORADNIK_DO_GRY_seq.NEXTVAL;
END;
/

--------------------------------------------------------------------------------
create table TWORZENIE_GRY (
  gra_id NUMBER,
  platforma_id NUMBER,
  studio_deweloperskie_id NUMBER,
  czas_powstawania NUMBER,
  budzet NUMBER
);
--------------------------------------------------------------------------------

create table RECENZJA (
  recenzja_id NUMBER,
  gra_id NUMBER,
  platforma_id NUMBER,
  autor_id NUMBER,
  tytul VARCHAR2(200),
  tekst VARCHAR2(200),
  tagi VARCHAR2(200)
);


CREATE SEQUENCE RECENZJA_seq;
CREATE OR REPLACE TRIGGER RECENZJA_seq_trg
BEFORE INSERT ON RECENZJA
FOR EACH ROW
BEGIN
  :NEW.recenzja_id := RECENZJA_seq.NEXTVAL;
END;
/
--------------------------------------------------------------------------------

create table KOMENTARZ_DO_RECENZJI (
  komentarz_do_recenzji_id NUMBER,
  gra_id NUMBER,
  recenzja_id NUMBER,
  data DATE,
  tekst VARCHAR2(200)
);

CREATE SEQUENCE KOMENTARZ_DO_RECENZJI_seq;
CREATE OR REPLACE TRIGGER KOMENTARZ_DO_RECENZJI_seq_trg
BEFORE INSERT ON KOMENTARZ_DO_RECENZJI
FOR EACH ROW
BEGIN
  :NEW.komentarz_do_recenzji_id := KOMENTARZ_DO_RECENZJI_seq.NEXTVAL;
END;
/
--------------------------------------------------------------------------------
ALTER TABLE WYDAWCA ADD CONSTRAINT WYDAWCA_pk PRIMARY KEY (wydawca_id);
ALTER TABLE UZYTKOWNIK ADD CONSTRAINT UZYTKOWNIK_pk PRIMARY KEY (uzytkownik_id);
ALTER TABLE GATUNEK ADD CONSTRAINT GATUNEK_pk PRIMARY KEY (gatunek_id);
ALTER TABLE STUDIO_DEWELOPERSKIE ADD CONSTRAINT STUDIO_DEWELOPERSKIE_pk PRIMARY KEY (studio_deweloperskie_id);
ALTER TABLE PLATFORMA ADD  CONSTRAINT PLATFORMA_pk PRIMARY KEY (platforma_id);
ALTER TABLE GRA ADD  CONSTRAINT gra_pk PRIMARY KEY (gra_id);
ALTER TABLE GRA ADD CONSTRAINT gra_fk FOREIGN KEY (gatunek_id) REFERENCES GATUNEK(gatunek_id);
ALTER TABLE WYDANIE_GRY ADD CONSTRAINT WYDANIE_GRY_pk PRIMARY KEY (gra_id, wydawca_id, platforma_id);
ALTER TABLE WYDANIE_GRY ADD CONSTRAINT WYDANIE_GRY_fk1 FOREIGN KEY (gra_id) REFERENCES GRA(gra_id);
ALTER TABLE WYDANIE_GRY ADD CONSTRAINT WYDANIE_GRY_fk2 FOREIGN KEY (wydawca_id) REFERENCES WYDAWCA(wydawca_id);
ALTER TABLE WYDANIE_GRY ADD CONSTRAINT WYDANIE_GRY_fk3 FOREIGN KEY (platforma_id) REFERENCES PLATFORMA(platforma_id);
ALTER TABLE KOMENTARZ_DO_GRY ADD CONSTRAINT KOMENTARZ_DO_GRY_pk PRIMARY KEY (komentarz_do_gry_id);
ALTER TABLE KOMENTARZ_DO_GRY ADD CONSTRAINT KOMENTARZ_DO_GRY_fk1 FOREIGN KEY (gra_id) REFERENCES GRA(gra_id);
ALTER TABLE KOMENTARZ_DO_GRY ADD CONSTRAINT KOMENTARZ_DO_GRY_fk2 FOREIGN KEY (uzytkownik_id) REFERENCES UZYTKOWNIK(uzytkownik_id);
ALTER TABLE PORADNIK_DO_GRY ADD CONSTRAINT PORADNIK_DO_GRY_pk PRIMARY KEY (poradnik_do_gry_id);
ALTER TABLE PORADNIK_DO_GRY ADD CONSTRAINT PORADNIK_DO_GRY_fk1 FOREIGN KEY (gra_id)         REFERENCES GRA(gra_id);
ALTER TABLE PORADNIK_DO_GRY ADD CONSTRAINT PORADNIK_DO_GRY_fk2 FOREIGN KEY (uzytkownik_id)  REFERENCES UZYTKOWNIK(uzytkownik_id);
ALTER TABLE PORADNIK_DO_GRY ADD CONSTRAINT PORADNIK_DO_GRY_fk3 FOREIGN KEY (platforma_id)   REFERENCES PLATFORMA(platforma_id);
ALTER TABLE TWORZENIE_GRY ADD CONSTRAINT TWORZENIE_GRY_pk PRIMARY KEY (gra_id, platforma_id);
ALTER TABLE TWORZENIE_GRY ADD CONSTRAINT TWORZENIE_GRY_fk1 FOREIGN KEY (gra_id) REFERENCES GRA(gra_id);
ALTER TABLE TWORZENIE_GRY ADD CONSTRAINT TWORZENIE_GRY_fk2 FOREIGN KEY (platforma_id) REFERENCES PLATFORMA(platforma_id);
ALTER TABLE TWORZENIE_GRY ADD CONSTRAINT TWORZENIE_GRY_fk3 FOREIGN KEY (studio_deweloperskie_id) REFERENCES STUDIO_DEWELOPERSKIE(studio_deweloperskie_id);
ALTER TABLE RECENZJA ADD CONSTRAINT RECENZJA_pk PRIMARY KEY (recenzja_id);
ALTER TABLE RECENZJA ADD CONSTRAINT recenzja_fk1 FOREIGN KEY (gra_id) REFERENCES GRA(gra_id);
ALTER TABLE RECENZJA ADD CONSTRAINT recenzja_fk2 FOREIGN KEY (platforma_id) REFERENCES PLATFORMA(platforma_id);
ALTER TABLE RECENZJA ADD CONSTRAINT recenzja_fk3 FOREIGN KEY (autor_id) REFERENCES UZYTKOWNIK(uzytkownik_id);
ALTER TABLE KOMENTARZ_DO_RECENZJI ADD CONSTRAINT KOMENTARZ_DO_RECENZJI_pk PRIMARY KEY (komentarz_do_recenzji_id);
ALTER TABLE KOMENTARZ_DO_RECENZJI ADD CONSTRAINT  KOMENTARZ_DO_RECENZJI_fk1 FOREIGN KEY (gra_id) REFERENCES GRA(gra_id);
ALTER TABLE KOMENTARZ_DO_RECENZJI ADD CONSTRAINT  KOMENTARZ_DO_RECENZJI_fk2 FOREIGN KEY (recenzja_id) REFERENCES RECENZJA(recenzja_id);

create or replace FUNCTION GENERATOR_DATY(POCZATEK_ROK in NUMBER, KONIEC_ROK IN NUMBER) 
RETURN DATE IS
	y NUMBER(4);
  d NUMBER(4);
  dates VARCHAR2(10);
BEGIN
	y := dbms_random.value(POCZATEK_ROK,KONIEC_ROK);
  d := dbms_random.value(1,355);
  dates := to_char(y) || to_char(d,'999');
  return to_date(dates,'yyyyddd');
END GENERATOR_DATY;
/

create or replace PROCEDURE GENERATOR_1(ILOSC in NUMBER) IS
BEGIN
	FOR i IN 1..ILOSC LOOP
		INSERT INTO UZYTKOWNIK VALUES (NULL, dbms_random.string('x', DBMS_RANDOM.VALUE(3,10)));
    INSERT INTO GATUNEK VALUES (NULL, dbms_random.string('x', DBMS_RANDOM.VALUE(3,10)));
    INSERT INTO PLATFORMA VALUES (NULL, dbms_random.string('x', DBMS_RANDOM.VALUE(3,10)));
    INSERT INTO WYDAWCA VALUES (NULL, dbms_random.string('x', DBMS_RANDOM.VALUE(3,10)));
	END LOOP;
END GENERATOR_1;
/

EXECUTE  GENERATOR_1(100);

INSERT INTO GRA (nazwa,gatunek_id,tagi) VALUES ('Counter Strike Global Offensive',1,'');
INSERT INTO GRA (nazwa,gatunek_id,tagi) VALUES ('Empire Earth 3',2,'');
INSERT INTO GRA (nazwa,gatunek_id,tagi) VALUES ('Flight Gear',5,'');
INSERT INTO GRA (nazwa,gatunek_id,tagi) VALUES ('FIFA 15',6,'');
INSERT INTO GRA (nazwa,gatunek_id,tagi) VALUES ('The Vanishing of Ethan Carter',4,'');
INSERT INTO GRA (nazwa,gatunek_id,tagi) VALUES ('Super Mario Bros',3,'');
INSERT INTO GRA (nazwa,gatunek_id,tagi) VALUES ('Populus',7,'');
INSERT INTO GRA (nazwa,gatunek_id,tagi) VALUES ('Counter Strike 1.6',1,'');
INSERT INTO GRA (nazwa,gatunek_id,tagi) VALUES ('League of Legends',8,'');
INSERT INTO GRA (nazwa,gatunek_id,tagi) VALUES ('Dying Light',1,'');
INSERT INTO GRA (nazwa,gatunek_id,tagi) VALUES ('Half Life',1,'');
INSERT INTO GRA (nazwa,gatunek_id,tagi) VALUES ('Portal',1,'');
INSERT INTO GRA (nazwa,gatunek_id,tagi) VALUES ('Crysis',1,'');
INSERT INTO GRA (nazwa,gatunek_id,tagi) VALUES ('Need for Speed: Most Wanted',9,'');
INSERT INTO GRA (nazwa,gatunek_id,tagi) VALUES ('Grand Theft Auto V',10,'');

INSERT INTO WYDANIE_GRY (gra_id,wydawca_id,platforma_id,data) VALUES (1,1,1,TO_DATE('21-08-2012'));
INSERT INTO WYDANIE_GRY (gra_id,wydawca_id,platforma_id,data) VALUES (8,1,1,TO_DATE('01-11-2000'));
INSERT INTO WYDANIE_GRY (gra_id,wydawca_id,platforma_id,data) VALUES (9,6,1,TO_DATE('07-10-2009'));
INSERT INTO WYDANIE_GRY (gra_id,wydawca_id,platforma_id,data) VALUES (10,2,1,TO_DATE('07-10-2009'));
INSERT INTO WYDANIE_GRY (gra_id,wydawca_id,platforma_id,data) VALUES (11,1,1,TO_DATE('19-11-1998'));
INSERT INTO WYDANIE_GRY (gra_id,wydawca_id,platforma_id,data) VALUES (12,1,1,TO_DATE('10-10-2007'));
INSERT INTO WYDANIE_GRY (gra_id,wydawca_id,platforma_id,data) VALUES (13,4,1,TO_DATE('16-10-2007'));
INSERT INTO WYDANIE_GRY (gra_id,wydawca_id,platforma_id,data) VALUES (14,4,1,TO_DATE('06-12-2005'));
INSERT INTO WYDANIE_GRY (gra_id,wydawca_id,platforma_id,data) VALUES (15,7,1,TO_DATE('14-04-2015'));
INSERT INTO WYDANIE_GRY (gra_id,wydawca_id,platforma_id,data) VALUES (15,7,2,TO_DATE('18-11-2014'));
INSERT INTO WYDANIE_GRY (gra_id,wydawca_id,platforma_id,data) VALUES (15,7,3,TO_DATE('17-09-2013'));
INSERT INTO WYDANIE_GRY (gra_id,wydawca_id,platforma_id,data) VALUES (15,7,4,TO_DATE('17-09-2013'));

select GRA.NAZWA,WYDAWCA.NAZWA as NAZWA_WYDAWCY,PLATFORMA.NAZWA as NAZWA_PLATFORMY,WYDANIE_GRY.DATA as DATA_WYDANIA
from GRA join WYDANIE_GRY on GRA.gra_id = WYDANIE_GRY.gra_id
join WYDAWCA on WYDANIE_GRY.wydawca_id = WYDAWCA.WYDAWCA_ID
join PLATFORMA on WYDANIE_GRY.platforma_id = PLATFORMA.platforma_id
order by WYDANIE_GRY.DATA;

commit;